### POST response to save the Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
"name": "Johnny  Do12tls 224",
"email": "Johnny.fsafds121s1006@example.com",
"address": "123 main street, 99024 Building, Sector 34",
"dateOfBirth": "1996-07-04",
"registeredDate":"2025-05-02"
}

###